default_platform(:ios)

platform :ios do
  lane :build do
    build_app(
      scheme: "AquaFaste",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.theknack.aquafaste" => "com.theknack.aquafaste AppStore"
        }
      },
      output_directory: "build",
      output_name: "AquaFaste.ipa",
      clean: true
    )
  end

  lane :upload do
    api_key = app_store_connect_api_key(
      key_id: "3PF72JBJ45",
      issuer_id: "0d7cd2d5-68c7-4214-854f-26b663d40beb",
      key_content: File.read(File.join(Dir.pwd, "fastlane", "AuthKey_3PF72JBJ45.p8")),
      is_key_content_base64: false,
      in_house: false
    )

    build
    
    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end
end
